"""Sunum sırası: rapordaki bölüm sıralamasına birebir uyar."""

SAHNELER = [
    ("s01_baslik.py",           "Baslik",              "Başlık"),
    ("s02_giris.py",            "Giris",               "1 · Giriş"),
    ("s03_nedir.py",            "FazGurultusuNedir",   "2 · Faz gürültüsü nedir?"),
    ("s04_zaman_frekans.py",    "ZamanFrekans",        "2.1 · Zaman ve frekans bölgesi"),
    ("s05_ssb.py",              "SSBTanimi",           "2.2 · Tek yan bant (SSB)"),
    ("s06_regrowth.py",         "EtkiRegrowth",        "3.1 · Spectral regrowth"),
    ("s07_reciprocal.py",       "EtkiReciprocal",      "3.2 · Reciprocal mixing"),
    ("s08_constellation.py",    "EtkiConstellation",   "3.3 · Haberleşme sistemleri"),
    ("s09_cesitler.py",         "GurultuCesitleri",    "4.1 · Spektral eğime göre"),
    ("s09_cesitler.py",         "OlcumTuru",           "4.2 · Ölçüm türüne göre"),
    ("s10_yontemler.py",        "YontemDogrudan",      "5.1 · Doğrudan spektral analiz"),
    ("s10_yontemler.py",        "YontemFazDetektoru",  "5.2 · Faz detektörü yöntemi"),
    ("s11_cross_yontem.py",     "YontemCross",         "5.3 · Cross-correlation yöntemi"),
    ("s12_vektor_ortalama.py",  "CrossVektorOrtalama", "5.3 · Yöntemin özü"),
    ("s13_model.py",            "ModelBlok",           "6 · Modelin işlem zinciri"),
    ("s13_model.py",            "GurultuUretimi",      "6.1 · Gürültü ve taşıyıcı üretimi"),
    ("s14_mikser.py",           "MikserKpd",           "6.2 · Mikser, LPF ve K_pd"),
    ("s16_kapsam.py",           "CrossPSDOrtalama",    "6.3 · Kompleks Cross-PSD"),
    ("s16_kapsam.py",           "LogBinlemeMAE",       "6.4 · Log binleme ve MAE"),
    ("s16_kapsam.py",           "Kapsam",              "6.5 · Modelin kapsamı"),
    ("s17_parametreler.py",     "KodAkisi",            "7.1 · Modelin fonksiyon akışı"),
    ("s15_asin.py",             "AsinOptimizasyon",    "7.2 · asin() optimizasyonu"),
    ("s17_parametreler.py",     "Optimizasyonlar",     "7.2 · Optimizasyon tablosu"),
    ("s17_parametreler.py",     "TemelParametreler",   "8.1 · Temel parametreler"),
    ("s18_taramalar.py",        "LPFTaramasi",         "8.2 · LPF kesim frekansı"),
    ("s18_taramalar.py",        "RMSTaramalari",       "8.3–8.4 · DUT ve referans RMS"),
    ("s18_taramalar.py",        "BinSayisi",           "8.5 · Logaritmik bin sayısı"),
    ("s19_iterasyon.py",        "IterasyonYakinsama",  "8.6 · İterasyon sayısı"),
    ("s19_iterasyon.py",        "DekadAnalizi",        "8.6 · Dekad bantlarında MAE"),
    ("s20_sonuc.py",            "PDvsCross",           "9 · PD ve çapraz korelasyon"),
    ("s20_sonuc.py",            "SonucKapanis",        "9 · Sonuç"),
    ("s20_sonuc.py",            "Kapanis",             "Kapanış"),
]
